name: ci

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
  watch:
    types: [started]
  workflow_dispatch:

jobs:
  autogreen:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
  
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Auto green
        run: |
          git config --local user.email "galubw@hotmail.com"
          git config --local user.name "ywbficmisse761"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "自动提交,啦啦啦"
          git push
